# Generated by Django 2.2.1 on 2020-07-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyaan', '0002_auto_20200723_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.TextField()),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now=True)),
                ('posted_by_id', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyaan.Domain')),
            ],
        ),
    ]
