# Generated by Django 2.2.1 on 2020-07-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyaan', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainexpert',
            old_name='user_id',
            new_name='expert_id',
        ),
        migrations.RenameField(
            model_name='domainfollower',
            old_name='user_id',
            new_name='follower_id',
        ),
    ]
