# Generated by Django 2.2.1 on 2020-07-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyaan', '0004_auto_20200723_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='title',
        ),
    ]
