# Generated by Django 2.2.1 on 2020-07-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyaan', '0005_auto_20200723_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_by_id', models.IntegerField()),
                ('commented_at', models.DateTimeField()),
                ('comment_content', models.TextField()),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gyaan.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyaan.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('LIKE', 'LIKE')], max_length=20)),
                ('reacted_by_id', models.IntegerField()),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gyaan.Comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gyaan.Post')),
            ],
        ),
    ]
