# Generated by Django 2.2.1 on 2020-08-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyaan', '0006_comment_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('is_domain_expert', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyaan.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='approved_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='DomainFollower',
        ),
    ]
