# Generated by Django 2.2.1 on 2020-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyaan', '0008_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='gyaan.Tag'),
        ),
    ]
